---
- src: git@github.com:xussof/software_snapd
  scm: git
  version: master
  name: xussof.software_snapd
- src: git@github.com:xussof/software_ansible
  scm: git
  version: master
  name: xussof.software_ansible
